server {
    listen 443 ssl; # ecoute sur le port 443, ssl permet d activer https
    server_name aandreo42.42.fr;

    ssl_certificate /etc/nginx/ssl/aandreo42.crt;
    ssl_certificate_key /etc/nginx/ssl/aandreo42.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}