services:
  mariadb:
  build:
    context: ./requirements/mariadb
  image: mariadb
  container_name: mariadb
  restart: always
  env_file:
    - .env
  secrets:
    - db_root_password
    - dp_user_password
  volumes:
    - db_data:/var/lib/mysql
  networks:
    - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aandreo/data/mariadb
networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  